### PR TITLE
Beginning of setup.py, following https://github.com/vene/pydai

### PR DESCRIPTION
**Pull request by fgregg**
Following @vene, compiling c library and then linking the cython extension to it. 

Seems to be working.

TODO, 
- [ ] decide on the namespace for the library, pystruct is expecting ad3, which conflicts with the directory structure of AD3, since the cpp source files are in that directory.
- [ ] Cythonize factor_graph.pyx so that cython is not a dependency for installing this library

### CODE REVIEW

**Comment by amueller** [comment]
As I said in the other thread, renaming to `AD3` in pystruct is fine with me. On the other hand it is not very pretty to have the c++ code in one folder and the python code in the other folder and rename the python package to avoid conflicts.

Also, I think introducing another name is more confusing. There is already a namespace for AD3 and Python is included in master.
Actually, I think it would be best if we could move all of it upstream.
If it is only a matter of a setup.py in the main directory, I'm pretty sure @andre-martins could be confinced to merge ;)

**Comment by amueller** [comment]
can't we have a python folder that contains an ad3 subfolder? or would that create trouble with the pip-installability?

**Comment by fgregg** [comment]
@amueller, I was thinking the same thing, and the last commit is the right solution I think

**Comment by amueller** [comment]
great. is travis still happy?

**Comment by fgregg** [comment]
Yes! https://travis-ci.org/pystruct/pystruct/builds/9109496#L860

**Comment by amueller** [comment]
Ok, great. I'll merge.
Then i'll move this one to the organization and add you to the organization if you don't mind ;)

**Pull request merged**
