### PR TITLE
[WIP] refactoring for 2.1 release

### PR DESCRIPTION
**Pull request by vene**
There have been quite a few changes upstream since the last release of the python wrapper, and it's not trivial at the moment to build and install the development version.  Here is my attempt at updating the wrapper and restructuring it to a slightly more conventional format (I think?)

The most important reason for the new release, to me, is to expose logic and tree factors.

I am not sure whether I should make this PR here or against @andre-martins 's original repo... the only divergence between the two seems to be the inclusion of the generated cpp.

### CODE REVIEW

**Comment by vene** [comment]
Fixed travis (it now successfully builds wheels and installs from them, even if there are no tests)

Added tree factor wrapper: check out [the notebook](https://github.com/vene/AD3/blob/newrel/pyexamples/parse_example.ipynb)

**Comment by vene** [comment]
Spammed a few commits while dealing with CI, but I got builds tested on both osx (with travis and default python 2.7) and on windows (under [my appveyor](https://ci.appveyor.com/project/vene/ad3).)

I also added a few simple tests to make sure everything is actually working and not just that it builds.

**Comment by amueller** [comment]
Sorry I'm swamped. I think it's better to do this upstream.

**Comment by vene** [comment]
Sure thing. Thanks!

**Comment by vene** [comment]
Closing this to move the work upstream.

**Pull request closed without merging**
